[versions]
okreplay = "1.6.0"
mockk = "1.9.3"

[libraries]
okreplay-core = { module = "com.airbnb.okreplay:okreplay", version.ref = "okreplay" }
okreplay-junit = { module = "com.airbnb.okreplay:junit", version.ref = "okreplay" }
junit4 = { module = "junit:junit", version = { prefer = "4.13.2" } }

mockk-core = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-dsl = { module = "io.mockk:mockk-dsl", version.ref = "mockk" }

kluent = { module = "org.amshove.kluent:kluent", version = { prefer = "1.65" } }

androidx-coreTesting = {module = "androidx.arch.core:core-testing", version = { prefer = "2.1.0" }}

android-robolectric = { module = "org.robolectric:robolectric", version = { prefer = "4.5.1" } }
android-barista = { module = "com.adevinta.android:barista", version = { prefer = "4.0.0" } }
android-fragmentTesting = { module = "androidx.fragment:fragment-testing", version = { prefer = "1.3.6" } }
android-junit = { module = "androidx.test.ext:junit", version = { prefer = "1.1.3" } }

[bundles]
mockk = [
    'mockk-core',
    'mockk-dsl',
]
okreplay = [
    "okreplay-core",
    "okreplay-junit",
]
